apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  CLIENT_URLS: "http://myapp.local"
  MONGO_URI: "mongodb://admin:admin123@mongodb-service:27017/streamingapp?authSource=admin"
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET: "streaming-app-bucket-254292659362"
  AWS_CDN_URL: "https://d2yzt1cprbew1o.cloudfront.net"
  STREAMING_PUBLIC_URL: "http://myapp.local:3002"
  REACT_APP_AUTH_API_URL: "/api/auth"
  REACT_APP_STREAMING_API_URL: "/api/streaming"
  REACT_APP_STREAMING_PUBLIC_URL: "/api/streaming"
  REACT_APP_ADMIN_API_URL: "/api/admin"
  REACT_APP_CHAT_API_URL: "api/chat"
  REACT_APP_CHAT_SOCKET_URL: "api/chat"

















