apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongoservice.fullname" . }}
  labels:
    {{- include "mongoservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
      protocol: TCP
      name: http
  selector:
    {{- include "mongoservice.selectorLabels" . | nindent 4 }}
